name: s-hnn
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pytorch=2.1
  - torchvision=0.16
  - torchaudio=2.1
  - ipykernel
  - jupyterlab
  - ipython
  - matplotlib-inline
  - pillow
  - scikit-learn
  - pip:
      - filelock==3.13.1
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - joblib==1.4.2
      - markupsafe==2.1.3
      - networkx==3.3
      - pip==24.2
      - python-dateutil==2.9.0.post0
      - setuptools==72.1.0
      - sympy==1.12
      - threadpoolctl==3.5.0
      - wheel==0.43.0
